name: Do noodle things
#  schedule:
#    - cron: '0 14 * * 1'
on:
  push:
    branches:
      - main
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5 - 3.8.5'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run the thingy
        run: python app.py
        env:
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}

      - name: push
        uses: actions-x/commit@v2
        with:
          name: GitHub Actions Autocommitter
          branch: main
          files: data/tweets.csv

#      - name: Commit changes
#        uses: EndBug/add-and-commit@v5
#        with:
#          message: "pulled data for sha ${{ env.GITHUB_SHA }}"
#          add: "data/tweets.csv"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}